Ny konsument for syfosoknad
navikt/flex-proxy pull request #7
Opened 2020-11-03 08:33 UTC by golshidb93

2020-11-05 09:52 UTC, heyvard requested changes

2020-11-05 09:52 UTC, heyvard commented on syfosoknad-proxy/nais-prod-gcp.yaml
> +    - "https://syfsoknad-proxy.nav.no/"
syfosoknad-proxy. typo. denne må også bestilles fra #tech-sikkerhet

2020-11-05 09:52 UTC, heyvard commented on syfosoknad-proxy/nais-prod-gcp.yaml
> +        - application: spinnsyn-backend
fjern denne

2020-11-05 09:52 UTC, heyvard commented on syfosoknad-proxy/nais-dev-gcp.yaml
> +        - application: syfosoknad
dette gjelder kun i samme namespace. Her skal du kalle api-gw. så trenge rheller external rule slik som i spinnsyn-backend https://github.com/navikt/spinnsyn-backend/blob/master/naiserator-dev.yaml#L48

2020-11-05 09:52 UTC, heyvard commented on syfosoknad-proxy/nais-prod-gcp.yaml
> +      value: "http://syfosoknad"
denne blir noe annet

2020-11-05 09:52 UTC, heyvard commented on syfosoknad-proxy/routes.yaml
> +    - /syfosoknad/api/veileder/internad/soknader
tror denne ikke trengs å eksponeres ut, de som kaller denen kjører i fss

2020-11-05 13:52 UTC, golshidb93 commented on syfosoknad-proxy/nais-prod-gcp.yaml
> +      value: "http://syfosoknad"
Både ALLOWED_ORIGINS og ERVICE_GATEWAY_URL?

2020-11-05 13:54 UTC, heyvard commented on syfosoknad-proxy/nais-prod-gcp.yaml
> +      value: "http://syfosoknad"
bare service gateway url, der skal du treffe api gatewayen. ala dette https://github.com/navikt/sykmelding-proxy/blob/main/sykmeldinger-backend-proxy/nais-dev-gcp.yaml#L47

2020-11-05 13:57 UTC, golshidb93 commented on syfosoknad-proxy/nais-dev-gcp.yaml
> +        - application: syfosoknad
Det er fordi vi krysser sone? er følgende riktig, eller mangler jeg noe?
  accessPolicy:
    outbound:
      external:
        - host: api-gw-q1.oera.no

2020-11-05 14:00 UTC, heyvard commented on syfosoknad-proxy/nais-dev-gcp.yaml
> +        - application: syfosoknad
det er nok riktig, men forskjellig i prod og q da

2020-11-05 14:40 UTC, heyvard requested changes

2020-11-05 14:40 UTC, heyvard commented on syfosoknad-proxy/routes.yaml
> +    - /api/soknader/:id/kafkaformat
denne kan fjernes, brukes kun internt i fss

2020-11-05 14:40 UTC, heyvard commented on syfosoknad-proxy/routes.yaml
> +    - /cronjob
kan også fjernes

2020-11-05 14:40 UTC, heyvard commented on syfosoknad-proxy/nais-prod-gcp.yaml
> +  env:
Du kommer til å trenge api gw key som en environment variabel

2020-11-06 13:00 UTC, heyvard approved these changes

2020-11-06 13:02 UTC, merged